name: Java CI

on:

  push:

    branches: [master]

  pull_request:

    branches: [master]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Set up JDK 1.8

        uses: actions/setup-java@v1

        with:

          java-version: 1.8

      - name: Set up Zsh

        run: sudo apt-get install zsh -y

      - name: Download Spigot

        run: |

          wget https://cdn.getbukkit.org/spigot/spigot-1.17.jar

      - name: Download libraries

        run: |
          wget https://repo1.maven.org/maven2/org/java-websocket/Java-WebSocket/1.4.0/Java-WebSocket-1.4.0.jar 
          wget https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.2/jython-standalone-2.7.2.jar

      - name: Build

        run: |
          #!/bin/zsh

          set -ex

          SPIGOT_JAR=spigot-1.17.jar

          WEBSOCKET_JAR=java-websocket-1.4.0.jar

          JYTHON_JAR=jython-standalone-2.7.2.jar

          pushd ServerPythonInterpreterPlugin

          rm -rf com/

          pushd src-common/

          javac -cp ".:../lib-spigot/${SPIGOT_JAR}:../lib-common/${WEBSOCKET_JAR}:../lib-common/${JYTHON_JAR}" ServerPythonInterpreterPlugin/src-common/com/macuyiko/minecraftpyserver/MinecraftPyServerPlugin.java
          popd

          jar cvf ../MinecraftPyServer.jar *.yml lib-common/ python/ com/

          popd

      - name: Upload artifact

        uses: actions/upload-artifact@v2

        with:

          name: artifact

          path: MinecraftPyServer.jar

