name: Java CI

on:

  push:

    branches: [master]

  pull_request:

    branches: [master]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Set up JDK 1.8

        uses: actions/setup-java@v1

        with:

          java-version: 1.8

      - name: Set up Zsh

        run: sudo apt-get install zsh -y

      - name: Download Spigot

        run: |

          wget https://cdn.getbukkit.org/spigot/spigot-1.17.jar

      - name: Download libraries

        run: |
          wget https://repo1.maven.org/maven2/org/python/jython-standalone/2.7.2/jython-standalone-2.7.2.jar

      - name: Build

        run: |

          pushd ServerPythonInterpreterPlugin

          rm -rf com/

          # Compile the plugin classes

          find . -name '*.java' -print | xargs javac -cp "../spigot-1.17.jar:../websocket-server-11.0.3.jar:../jython-standalone-2.7.2.jar" -d .. -sourcepath .

          pushd src-common/

          jar cvf ../MinecraftPyServer.jar *.yml lib-common/ python/ com/

          popd

          popd

      - name: Upload artifact

        uses: actions/upload-artifact@v2

        with:

          name: artifact

          path: MinecraftPyServer.jar

